name: CUT&TAG test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  test-cutTag:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # default to bash shell
    steps:
      - name: 0 - Sync main and test # -----------------------------------------------------------
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: main
          TO_BRANCH: test

      - name: 0 - Conda cache # -------------------------------------------------------------------
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}--${{ runner.arch }}-${{ hashFiles('.test/testdata/snakemake.5.32.yaml') }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: 1 - Check out test branch # ---------------------------------------------------------
        uses: actions/checkout@v3
        with:
          ref: 'test'

      - name: 2 - Install Conda and SnakeMake # ---------------------------------------------------
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: snakemake
          environment-file: .test/testdata/snakemake.5.32.yaml
          use-only-tar-bz2: true
          use-mamba: true

      - name: 3 - Activate Conda Environment # ----------------------------------------------------
        run: |
            tree
            echo ----------
            tree .test
            conda init bash
            source ~/.bashrc
            source activate snakemake
            conda info
            conda list
            # make sure testing sub-folder has up-to-date scripts
            mkdir -p .test/src
            cp -r src .test/src

      - name: 4 - Prepare the Snake # -------------------------------------------------------------
        run: |
          source activate /usr/share/miniconda/envs/snakemake
          snakemake -j 1 -np --directory .test
          snakemake -j 2 --use-conda --conda-frontend mamba --conda-create-envs-only --directory .test

      - name: 5  - Bowtie2 Index # ----------------------------------------------------------------
        run: |
          cd .test
          source activate .snakemake/conda/c5ec7e8d 
          bowtie2-build --thread 4 testdata/Homo_sapiens.GRCh38.dna_rm.chromosome.1.fa.gz testdata/hg38_chr1
          cd ..

      - name: 6 - Run the Snake # -----------------------------------------------------------------
        run: |
          source activate /usr/share/miniconda/envs/snakemake
          snakemake -j 2 --use-conda --directory .test --keep-going
          tree .test

